kind: pipeline
type: docker
name: api-project
workspace:
  base: /data/drone
  path: api-project

trigger:
  branch:
    - master
  event:
    - push

clone:
  depth: 1

steps:
  - name: test
    image: golang
    volumes:
      - name: go-build-cache
        path: /go/go-build
      - name: go-pkg-cache
        path: /go/pkg
    environment:
      GOCACHE: /go/go-build
    commands:
      - go mod tidy
      - go test

  - name: build-app
    image: golang
    volumes:
      - name: go-build-cache
        path: /go/go-build
      - name: go-pkg-cache
        path: /go/pkg
    environment:
      GOCACHE: /go/go-build
    commands:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app

  - name: build-image
    image: plugins/docker
    settings:
      username:
        from_secret: docker-user
      password:
        from_secret: docker-password
      repo: ccr.ccs.tencentyun.com/wwww/api-project
      tags:
        - ${DRONE_BUILD_CREATED}
        - latest
      dockerfile: ./Dockerfile
      registry: https://ccr.ccs.tencentyun.com

  - name: deploy-api
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh-host
      username:
        from_secret: ssh-user
      password:
        from_secret: ssh-password
      script:
        - kubectl set image deploy app-api-project app=ccr.ccs.tencentyun.com/wwww/api-project:${DRONE_BUILD_CREATED} --namespace magic

  - name: notify
    image: kaynewang/drone-wechat-robot
    settings:
      msgtype: markdown
      key: "c10e1711-aec4-476f-9d8a-badfb4b2d3df"
      content: |
        ### 部署通知
        > 仓库名字: ${DRONE_REPO_NAME}
        > 提交作者: ${DRONE_COMMIT_AUTHOR}
        > 提交记录: ${DRONE_COMMIT_MESSAGE}
        > 提交链接: ${DRONE_COMMIT_LINK}
        > 构建标签: ${DRONE_BUILD_CREATED}
        > 构建状态: ${DRONE_BUILD_STATUS}
    when:
      status:
        - success
        - failure


# 挂载的目录
# 缓存go-build($GOCACHE)路径
# 缓存go-pkg目录
volumes:
  - name: go-build-cache
    host:
      path: /tmp/cache/go/go-build
  - name: go-pkg-cache
    host:
      path: /tmp/cache/go/pkg